import { faker } from "@faker-js/faker";
import { config } from "dotenv";
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { analysisItems, roasts } from "./schema";

config({ path: ".env.local" });

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
	throw new Error("DATABASE_URL is not set");
}

const db = drizzle(databaseUrl, { casing: "snake_case" });

const LANGUAGES = [
	"javascript",
	"typescript",
	"python",
	"java",
	"go",
	"rust",
	"c",
	"cpp",
	"ruby",
	"php",
	"swift",
	"kotlin",
	"sql",
	"html",
	"css",
	"bash",
] as const;

const VERDICTS = [
	"needs_serious_help",
	"rough_around_edges",
	"decent_code",
	"solid_work",
	"exceptional",
] as const;

const SEVERITIES = ["critical", "warning", "good"] as const;

const CODE_SNIPPETS: Record<string, string[]> = {
	javascript: [
		`function sum(arr) {
  var total = 0;
  for (var i = 0; i < arr.length; i++) {
    total = total + arr[i];
  }
  return total;
}`,
		`eval(prompt("enter code"))
document.write(response)
// trust the user lol`,
		`const fetchData = async () => {
  try {
    const res = await fetch("/api/data");
    const data = await res.json();
    return data;
  } catch (e) {
    console.log(e);
  }
}`,
		`if (x == true) {
  return true;
} else if (x == false) {
  return false;
} else {
  return null;
}`,
		`document.getElementById("btn").onclick = function() {
  document.getElementById("output").innerHTML = document.getElementById("input").value;
}`,
	],
	typescript: [
		`function getUser(id: any): any {
  const user = db.query("SELECT * FROM users WHERE id = " + id);
  return user;
}`,
		`interface Props {
  name: string;
  age: number;
  email: string;
}

const Component = (props: Props) => {
  return <div>{props.name} - {props.age} - {props.email}</div>
}`,
		`const handler = async (req: Request): Promise<Response> => {
  const body = await req.json() as any;
  const result = await processData(body);
  return new Response(JSON.stringify(result));
}`,
	],
	python: [
		`def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)`,
		`import os
password = input("Enter password: ")
os.system(f"echo {password} | sudo -S apt-get update")`,
		`class User:
    def __init__(self, name, age, email):
        self.name = name
        self.age = age
        self.email = email

    def to_dict(self):
        return {"name": self.name, "age": self.age, "email": self.email}`,
	],
	java: [
		`public class Main {
    public static void main(String[] args) {
        ArrayList list = new ArrayList();
        list.add("hello");
        list.add(42);
        list.add(true);
        System.out.println(list);
    }
}`,
		`public String processInput(String input) {
    String query = "SELECT * FROM users WHERE name = '" + input + "'";
    return db.execute(query);
}`,
	],
	go: [
		`func divide(a, b int) int {
	return a / b
}`,
		`func readFile(path string) string {
	data, _ := os.ReadFile(path)
	return string(data)
}`,
	],
	rust: [
		`fn main() {
    let mut v = vec![1, 2, 3];
    for i in &v {
        v.push(*i * 2);
    }
}`,
		`fn parse_number(s: &str) -> i32 {
    s.parse::<i32>().unwrap()
}`,
	],
	sql: [
		`SELECT * FROM users WHERE 1=1;
DELETE FROM logs;`,
		`SELECT u.*, o.*, p.*
FROM users u, orders o, products p
WHERE u.id = o.user_id AND o.product_id = p.id;`,
	],
	php: [
		`<?php
$name = $_GET['name'];
echo "Hello, $name!";
$conn = mysql_connect("localhost", "root", "");
?>`,
		`<?php
function calculateDiscount($price, $discount) {
    return $price - ($price * $discount / 100);
}
echo calculateDiscount(100, 20);
?>`,
	],
	ruby: [
		`def greet(name)
  puts "Hello, #{name}!"
rescue => e
  puts e.message
end`,
	],
	swift: [
		`func forceUnwrap(value: String?) -> String {
    return value!
}`,
	],
	kotlin: [
		`fun main() {
    val list = mutableListOf<Any>()
    list.add("hello")
    list.add(42)
    println(list)
}`,
	],
	html: [
		`<html>
<body>
<marquee><blink>Welcome to my website!</blink></marquee>
<font size="7" color="red">HELLO WORLD</font>
</body>
</html>`,
	],
	css: [
		`* {
  margin: 0 !important;
  padding: 0 !important;
  float: left !important;
}`,
	],
	bash: [
		`rm -rf /
echo "cleaned up disk space"`,
		`chmod 777 *
echo "fixed permissions"`,
	],
	c: [
		`#include <stdio.h>
void main() {
    char buffer[10];
    gets(buffer);
    printf(buffer);
}`,
	],
	cpp: [
		`#include <iostream>
using namespace std;
int main() {
    int* ptr = new int[100];
    cout << ptr[0] << endl;
    // forgot to delete
    return 0;
}`,
	],
};

const ROAST_QUOTES = [
	"this code was written during a power outage... in 2005.",
	"I've seen better code generated by a cat walking on a keyboard.",
	"this is what happens when Stack Overflow is down.",
	"congratulations, you've invented a new anti-pattern.",
	"this code doesn't just have bugs, it IS a bug.",
	"I'm not angry, I'm just disappointed.",
	"the compiler called. it wants an apology.",
	"this code has more red flags than a communist parade.",
	"did you write this with your eyes closed?",
	"this is a masterclass in how NOT to write code.",
	"I'd suggest a rewrite, but that implies there was a write to begin with.",
	"even ChatGPT would refuse to generate this.",
	"your variable names are more confusing than IKEA assembly instructions.",
	"this function does more things than a Swiss Army knife, and none of them well.",
	"at least it's consistently bad.",
	"the indentation alone is a crime against humanity.",
	"I've seen spaghetti more organized than this code.",
	"this code violates the Geneva Convention.",
	"somewhere, a senior developer is crying.",
	"the only thing this code catches is feelings.",
	"not bad. I mean, it IS bad, but I've seen worse. barely.",
	"decent structure, questionable life choices.",
	"clean enough that I only screamed twice.",
	"surprisingly readable for something that doesn't work.",
	"solid fundamentals buried under layers of chaos.",
	"you clearly know what you're doing. why aren't you doing it?",
	"this is actually... good? I need to sit down.",
	"well-structured, clean, and efficient. who are you?",
	"the code equivalent of a perfectly organized bookshelf.",
	"I came to roast but stayed to admire.",
];

const ISSUE_TITLES: Record<string, string[]> = {
	critical: [
		"SQL injection vulnerability",
		"using eval() with user input",
		"hardcoded credentials",
		"buffer overflow risk",
		"missing input validation",
		"unhandled promise rejection",
		"race condition detected",
		"memory leak in loop",
		"using deprecated API",
		"insecure data transmission",
	],
	warning: [
		"using var instead of const/let",
		"imperative loop pattern",
		"missing error handling",
		"deeply nested callbacks",
		"magic numbers in code",
		"function too long",
		"excessive type casting",
		"mutable state in shared scope",
		"inconsistent naming convention",
		"missing return type annotation",
	],
	good: [
		"clear naming conventions",
		"single responsibility principle",
		"proper error handling",
		"good use of destructuring",
		"clean function signatures",
		"consistent code style",
		"appropriate use of generics",
		"well-structured imports",
		"readable control flow",
		"proper encapsulation",
	],
};

const ISSUE_DESCRIPTIONS: Record<string, string[]> = {
	critical: [
		"user input is being directly interpolated into a query string. use parameterized queries to prevent injection attacks.",
		"eval() executes arbitrary code from user input. this is a critical security vulnerability that allows remote code execution.",
		"credentials are hardcoded in the source code. use environment variables or a secrets manager instead.",
		"writing to a fixed-size buffer without bounds checking. this can lead to memory corruption and security exploits.",
		"no validation on user-provided data before processing. this can lead to unexpected behavior or security issues.",
		"async operations without catch blocks will crash the process on rejection in strict mode.",
		"concurrent access to shared mutable state without synchronization can produce unpredictable results.",
		"objects allocated inside a loop are never freed, causing memory usage to grow unbounded.",
		"this API has been deprecated and may be removed in future versions. migrate to the recommended alternative.",
		"sensitive data is being sent over an unencrypted channel. use HTTPS/TLS for all data transmission.",
	],
	warning: [
		"var is function-scoped and leads to hoisting bugs. use const by default, let when reassignment is needed.",
		"for loops are verbose and error-prone. use .reduce() or .map() for cleaner, functional transformations.",
		"no try/catch or error callback. if this fails, the error will propagate silently or crash the app.",
		"callback nesting beyond 3 levels hurts readability. consider using async/await or extracting helper functions.",
		"unexplained numeric literals scattered in code. extract them into named constants for clarity.",
		"this function exceeds 50 lines. break it down into smaller, focused functions for better testability.",
		"excessive use of 'as any' bypasses type safety. define proper types or use type guards instead.",
		"shared mutable state makes the code hard to reason about and test. consider immutable patterns.",
		"mixing camelCase, snake_case, and PascalCase in the same scope. pick one convention and stick to it.",
		"functions without explicit return types rely on inference, which can lead to accidental type changes.",
	],
	good: [
		"calculateTotal and items are descriptive, self-documenting names that communicate intent without comments.",
		"the function does one thing well — no side effects, no mixed concerns, no hidden complexity.",
		"errors are caught, logged, and handled gracefully with appropriate fallback behavior.",
		"good use of destructuring to extract only the needed properties, keeping the code concise.",
		"function parameters are well-typed with clear defaults, making the API easy to understand and use.",
		"consistent indentation, spacing, and formatting throughout. the codebase looks professionally maintained.",
		"generics are used appropriately to create flexible, reusable abstractions without sacrificing type safety.",
		"imports are organized logically — external libs first, then internal modules, then relative paths.",
		"the control flow is linear and easy to follow. no deeply nested conditionals or early returns that confuse.",
		"implementation details are properly hidden behind a clean public interface.",
	],
};

function getVerdictForScore(score: number): (typeof VERDICTS)[number] {
	if (score <= 2) return "needs_serious_help";
	if (score <= 4) return "rough_around_edges";
	if (score <= 6) return "decent_code";
	if (score <= 8) return "solid_work";
	return "exceptional";
}

function pickRandom<T>(arr: readonly T[]): T {
	return arr[Math.floor(Math.random() * arr.length)];
}

function generateCodeSnippet(language: string): string {
	const snippets = CODE_SNIPPETS[language];
	if (snippets && snippets.length > 0) {
		return pickRandom(snippets);
	}
	return `// ${language} code\nfunction example() {\n  return "hello";\n}`;
}

function generateSuggestedFix(code: string): string {
	const lines = code.split("\n");
	const improved = lines.map((line) => {
		return line
			.replace(/\bvar\b/g, "const")
			.replace(/\beval\b/g, "/* removed eval */")
			.replace(/== true/g, "")
			.replace(/== false/g, "!")
			.replace(/console\.log/g, "console.error");
	});
	return improved.join("\n");
}

function generateAnalysisItems(score: number): {
	severity: (typeof SEVERITIES)[number];
	title: string;
	description: string;
}[] {
	const itemCount = faker.number.int({ min: 2, max: 6 });
	const items: {
		severity: (typeof SEVERITIES)[number];
		title: string;
		description: string;
	}[] = [];

	for (let i = 0; i < itemCount; i++) {
		let severity: (typeof SEVERITIES)[number];

		if (score <= 3) {
			severity = pickRandom(["critical", "critical", "warning"] as const);
		} else if (score <= 6) {
			severity = pickRandom([
				"critical",
				"warning",
				"warning",
				"good",
			] as const);
		} else {
			severity = pickRandom(["warning", "good", "good", "good"] as const);
		}

		const titles = ISSUE_TITLES[severity];
		const descriptions = ISSUE_DESCRIPTIONS[severity];

		items.push({
			severity,
			title: pickRandom(titles),
			description: pickRandom(descriptions),
		});
	}

	return items;
}

async function seed() {
	console.log("Seeding database with 100 roasts...\n");

	await db.delete(analysisItems);
	await db.delete(roasts);

	let insertedRoasts = 0;
	let insertedItems = 0;

	for (let i = 0; i < 100; i++) {
		const language = pickRandom(LANGUAGES);
		const code = generateCodeSnippet(language);
		const lineCount = code.split("\n").length;
		const roastMode = faker.datatype.boolean({ probability: 0.6 });
		const score =
			Math.round(
				faker.number.float({ min: 0.5, max: 10, fractionDigits: 1 }) * 10,
			) / 10;
		const verdict = getVerdictForScore(score);
		const roastQuote = roastMode
			? pickRandom(ROAST_QUOTES)
			: pickRandom(ROAST_QUOTES.slice(20));
		const suggestedFix = score <= 7 ? generateSuggestedFix(code) : null;
		const createdAt = faker.date.recent({ days: 90 });

		const [roast] = await db
			.insert(roasts)
			.values({
				code,
				language,
				lineCount,
				roastMode,
				score,
				verdict,
				roastQuote,
				suggestedFix,
				createdAt,
			})
			.returning({ id: roasts.id });

		const items = generateAnalysisItems(score);

		if (items.length > 0) {
			await db.insert(analysisItems).values(
				items.map((item, index) => ({
					roastId: roast.id,
					severity: item.severity,
					title: item.title,
					description: item.description,
					order: index,
				})),
			);
			insertedItems += items.length;
		}

		insertedRoasts++;
	}

	console.log(`Inserted ${insertedRoasts} roasts`);
	console.log(`Inserted ${insertedItems} analysis items`);

	const [stats] = await db
		.select({
			total: sql<number>`count(*)`,
			avg: sql<number>`round(avg(${roasts.score})::numeric, 1)`,
		})
		.from(roasts);

	console.log(`\nStats: ${stats.total} roasts, avg score: ${stats.avg}/10`);

	process.exit(0);
}

seed().catch((err) => {
	console.error("Seed failed:", err);
	process.exit(1);
});
